[build]
  publish = "public"
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.58.1"
  HUGO_ENABLEGITINFO = "false"
  NODE_ENV = "production"
  command = "npm run build"